name: DevBlog CI/CD Pipeline

# ¿Cuándo se ejecuta este pipeline?
on:
  push:
    branches: [ main, develop ] # En push a main o develop
  pull_request:
    branches: [ main ] # En pull requests a main

# Variables de entorno globales
env:
  PYTHON_VERSION: '3.11'
  NODE_VERSION: '18'

# Jobs (trabajos) que se ejecutarán
jobs:
  # ================================
  # JOB 1: TESTING
  # ================================
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      # Paso 1: Descargar código del repositorio
      - name: Checkout code
        uses: actions/checkout@v4
      
      # Paso 2: Configurar Python
      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      
      # Paso 3: Cache de dependencias (optimización)
      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      
      # Paso 4: Instalar dependencias
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      # Paso 5: Ejecutar tests con cobertura
      - name: Run tests with coverage
        run: |
          pytest --cov=app --cov-report=xml --cov-report=term-missing -v
      
      # Paso 6: Subir reporte de cobertura (ACTUALIZADO)
      - name: Upload coverage reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: coverage-report
          path: coverage.xml
          retention-days: 30

  # ================================
  # JOB 2: DOCKER BUILD
  # ================================
  docker-build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    needs: test # Solo se ejecuta si los tests pasan
    steps:
      # Paso 1: Descargar código
      - name: Checkout code
        uses: actions/checkout@v4
      
      # Paso 2: Configurar Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      # Paso 3: Construir imagen Docker
      - name: Build Docker image
        run: |
          docker build -t devblog:${{ github.sha }} .
          docker build -t devblog:latest .
      
      # Paso 4: Probar que la imagen funciona
      - name: Test Docker image
        run: |
          # Ejecutar contenedor en background
          docker run -d -p 5000:5000 --name test-container devblog:latest
          # Esperar que inicie (ACTUALIZADO: 15 segundos)
          sleep 15
          # Probar que responde
          curl -f http://localhost:5000/ || exit 1
          curl -f http://localhost:5000/api/posts || exit 1
          # Limpiar
          docker stop test-container
          docker rm test-container

  # ================================
  # JOB 3: SECURITY SCAN
  # ================================
  security:
    name: Security Scan
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      
      # Escaneo de vulnerabilidades en dependencias (ACTUALIZADO)
      - name: Install security tools
        run: |
          pip install safety bandit
      
      - name: Run safety check
        run: |
          safety check -r requirements.txt --json --output safety-report.json || true
          echo "Safety check completed"
      
      # Análisis de código estático
      - name: Run bandit security linter
        run: |
          bandit -r app/ -f json -o bandit-report.json || true
          echo "Bandit scan completed"
      
      # Subir reportes (ACTUALIZADO)
      - name: Upload security reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: security-reports
          path: |
            safety-report.json
            bandit-report.json
          retention-days: 30

  # ================================
  # JOB 4: DEPLOY (solo en main)
  # ================================
  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: [test, docker-build, security]
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Deploy notification
        run: |
          echo "All tests passed! Ready for deployment!"
          echo "Test results: Passed"
          echo "Docker build: Success"
          echo "Security scan: Passed"
          echo "Deployment would happen here..."